/**
 * Autogenerated by Thrift Compiler (0.9.3)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#ifndef tair_service_CONSTANTS_H
#define tair_service_CONSTANTS_H

#include "tair_service_types.h"

namespace tair_thrift {

class tair_serviceConstants {
 public:
  tair_serviceConstants();

};

extern const tair_serviceConstants g_tair_service_constants;

} // namespace

#endif
