/**
 * Autogenerated by Thrift Compiler (0.9.3)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#ifndef tair_service_TYPES_H
#define tair_service_TYPES_H

#include <iosfwd>

#include <thrift/Thrift.h>
#include <thrift/TApplicationException.h>
#include <thrift/protocol/TProtocol.h>
#include <thrift/transport/TTransport.h>

#include <thrift/cxxfunctional.h>


namespace tair_thrift {

class tair_data_pair;

typedef struct _tair_data_pair__isset {
  _tair_data_pair__isset() : len(false), data(false) {}
  bool len :1;
  bool data :1;
} _tair_data_pair__isset;

class tair_data_pair {
 public:

  tair_data_pair(const tair_data_pair&);
  tair_data_pair& operator=(const tair_data_pair&);
  tair_data_pair() : len(0), data() {
  }

  virtual ~tair_data_pair() throw();
  int64_t len;
  std::string data;

  _tair_data_pair__isset __isset;

  void __set_len(const int64_t val);

  void __set_data(const std::string& val);

  bool operator == (const tair_data_pair & rhs) const
  {
    if (!(len == rhs.len))
      return false;
    if (!(data == rhs.data))
      return false;
    return true;
  }
  bool operator != (const tair_data_pair &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const tair_data_pair & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

  virtual void printTo(std::ostream& out) const;
};

void swap(tair_data_pair &a, tair_data_pair &b);

inline std::ostream& operator<<(std::ostream& out, const tair_data_pair& obj)
{
  obj.printTo(out);
  return out;
}

} // namespace

#endif
