/**
 * Autogenerated by Thrift Compiler (0.9.3)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#include "tair_service_constants.h"

namespace tair_thrift {

const tair_serviceConstants g_tair_service_constants;

tair_serviceConstants::tair_serviceConstants() {
}

} // namespace

